### PR TITLE
reformatted JavaScript modules with Prettier

### PR DESCRIPTION
**Pull request by FND**
→ [Prettier](https://prettier.io)

> this ensures consistency without inducing unnecessary overhead/headaches (modulo OCD)

90266e4fe00b394a2a9d8d90ab848ae8e35585e2

with a crowd of contributors this diverse (screw whitespace privilege ✊ ), opinionated auto-formatting seems [better than the alternative](https://www.youtube.com/watch?v=lR9WjYi-G2Q) 🤕

caveats:

* contributors are expected to run `npm run format`, before every single commit
* formatting is not currently being verified by CI
* a few of Prettier's opinions reduce readability¹ - since it's (intentionally) not highly configurable, we'll probably have to live with that; see above

¹ notably the lack of double indentation for line continuations as well as spurious parentheses (and additional indentation) around XML blocks - feel free to join in with your own ineffectual whining

### CODE REVIEW

**Comment by moonglum** [comment]
I configured CI to check for appeasing you, we could do the same thing with `prettier`: https://prettier.io/docs/en/cli.html#list-different

**Comment by FND** [comment]
I know; `npm run format -- --list-different` should work just fine - but _ideally_, we'd check individual commits for violations. However, that seems complex and we didn't do that with ESLint either, so only checking the latest commit should suffice.

**Comment by FND** [comment]
I've adjusted `npm test` to also verify Prettier formatting - feel free to merge.

Note that I opted to include `--list-different` directly in the "format" script - the downside of that is that deviations will result in the script erroring out (though it will still perform reformatting).

**Review by moonglum — APPROVED** [review]
I give my 👍

**Comment by FND** [comment]
merged as 019132f9ed5f4196d28c8eb6501c4f41cd26b321

**Pull request closed without merging**
